name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v2
      with:
            swift-version: "5.10"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
